"""date

Revision ID: 7793ad9963a9
Revises: 93b9ea5a5767
Create Date: 2021-01-27 10:10:00.610372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7793ad9963a9'
down_revision = '93b9ea5a5767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('when', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'when')
    # ### end Alembic commands ###
