"""added when 

Revision ID: 87a82d200552
Revises: aba4932a7c89
Create Date: 2020-11-06 19:05:40.404557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a82d200552'
down_revision = 'aba4932a7c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('when', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'when')
    # ### end Alembic commands ###
