"""media added

Revision ID: 913e0c26a9a7
Revises: ee6eb65ee20d
Create Date: 2020-10-18 13:38:28.966926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '913e0c26a9a7'
down_revision = 'ee6eb65ee20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('product', 'media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('media', mysql.TEXT(), nullable=False))
    op.drop_table('media')
    # ### end Alembic commands ###
