"""order 

Revision ID: d6de3b7cc18f
Revises: bc5b2f7ba073
Create Date: 2021-01-10 17:59:58.766961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6de3b7cc18f'
down_revision = 'bc5b2f7ba073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'location')
    op.drop_column('order', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('order', sa.Column('location', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
